### PR TITLE
My Implementation of the Quote app

### PR DESCRIPTION
**Pull request by ssouris**

### CODE REVIEW

**Comment by tsegismont** [comment]
@ssouris hi, thanks for submitting. Which project are you interested in?

**Comment by ssouris** [comment]
@tsegismont hi, thanks for reviewing the PR. I would be really interested in the `Reactive Blockchain client`, although I am not a student anymore and I don't know how I could participate in it.

**Comment by tsegismont** [comment]
@ssouris I haven't reviewed it. If you're interested in the blockchain client, @pmlopes would.

But anyway, if you're not a student anymore, you can't participate: https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation

**Comment by ssouris** [comment]
ok I see, thanks

**Pull request closed without merging**
